### ISSUE TITLE
Replace tools.go with something else

### ISSUE THREAD

**Issue by invidian** [tinkerbell/terraform-provider-tinkerbell#21]
We have right now `tools.go` file which pulls goreleaser as a dependency, so we're able to use `go run` to run it and `go run` would not modify the `go.mod` file etc. This unfortunately pulls a lot of indirect dependencies, which may cause some confusion.

I think we should be able to replace it with `go run -mod=mod`. However, using it this way does not allow versioning the tooling versions.

See also https://github.com/tinkerbell/terraform-provider-tinkerbell/pull/20#discussion_r542100422

**Comment by mmlb** [comment]
Embrace nixpkgs for this? I dont really know of an alternative that would allow pinned versions. Either we piggy back on go mod and live with go tracking tool dependencies or we try an external system. I like nix because it can be setup as a dev env along with just a build env/tool. Going in on nix in all of tinkerbell would benefit from homogeneity of build and dev env and can be pretty straight forward if documented properly.

**Comment by invidian** [comment]
What's wrong with approach from 1d2377d ?

**Comment by mmlb** [comment]
Its not seamless and you have to remember to run with the right mod file when doing something that uses it, if you don't go ends up using something else silently right? Having multiple mod files just feels like extra work.

contrast that with nix for example, if you pair it with direnv you cd into the project dir and everything is all setup.

**Comment by invidian** [comment]
I think all tasks should be automated with `Make` anyway, so I don't feel like there is anything extra to remember here. Even inside `Makefile` we can have `GO_TOOLS_RUN="go -mod=go.tools.mod"` to avoid duplication.

**Comment by mmlb** [comment]
Yeah the use case here is alright, though I think it still misses things like handling updates to the mod file for example. I guess I was making a more overarching / umbrella project statement which I think is actually better as a proposal.
